import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./componentes/Navbar"
import Container from "./componentes/Container"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Container>
          <main>
            <Navbar />
            {children}
          </main>
        </Container>
      </body>
    </html>
  )
}
